In [4]:
import numpy as np
import time

In [6]:
a = np.zeros(4)
print(f'np.zeros: a = {a}, a shape = {a.shape},a data type = {a.dtype}' )

np.zeros: a = [0. 0. 0. 0.], a shape = (4,),a data type = float64


In [28]:
a = np.random.random_sample(4)
print(a)

[0.63629904 0.51595285 0.03940756 0.66908335]


In [20]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [26]:
a = np.random.rand(4)
print(a)

[0.4932077  0.58009237 0.99045808 0.09138647]


In [30]:
a = np.array([1,3,4])
print(a)

[1 3 4]


3.4 Operations on Vectors

In [40]:
a = np.arange(10)
a
# print(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a[3]

3

In [48]:
a[-1]

9

In [67]:
try:
    c = a[10]
    print(c)
except Exception as e:
    print("The error message you'll see is")
    print(e)

The error message you'll see is
index 10 is out of bounds for axis 0 with size 10


# Slicing

In [72]:
a = np.arange(10) 
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [81]:
a[:2]

array([0, 1])

In [90]:
a[1:7:1]

array([1, 2, 3, 4, 5, 6])

In [94]:
a[1:7:2]

array([1, 3, 5])

In [96]:
a[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [104]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

 Single vector operations

In [132]:
a = np.array([1,2,3,4])
print(a)
b = -a
print(b)

c = np.sum(a)
print(c)

d = np.mean(a)
print(d)

e = a ** 2
print(e)


[1 2 3 4]
[-1 -2 -3 -4]
10
2.5
[ 1  4  9 16]


3.4.4 Vector Vector element-wise operations
Most of the NumPy arithmetic, logical and comparison operations apply to vectors as well. These operators work on an element-by-element basis. For example
𝑐𝑖=𝑎𝑖+𝑏𝑖

In [135]:
a = np.array([1, 2, 3, 4])
b = np.array([-1, -2, 3, 4])
print(f"Binary operations work element wise: {a + b} " )

Binary operations work element wise: [0 0 6 8] 


In [137]:
#try a mismatched vector operation

c = np.array([1,2])
try:
    d = a + c
    print(d)
except Exception as e:
    print('The Error message you will see as:')
    print(e)
    

The Error message you will see as:
operands could not be broadcast together with shapes (4,) (2,) 


3.4.5 Scalar Vector operations
Vectors can be 'scaled' by scalar values. A scalar value is just a number. The scalar multiplies all the elements of the vector.



In [142]:
a = np.array([1,2,3,4])
b = 5 * a
print(b)

[ 5 10 15 20]


3.4.6 Vector Vector dot product
The dot product is a mainstay of Linear Algebra and NumPy. This is an operation used extensively in this course and should be well understood. The dot product is shown below.

In [179]:
def my_dot(a,b):
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x 
a = np.array([1,2,3])
b = np.array([4,5,6])
tic = time.time()
print(my_dot(a,b))
toc = time.time()
print(toc - tic)

32
0.00013113021850585938


In [181]:
a = np.array([1,2,3])
b = np.array([4,5,6])
tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(c)
print(toc - tic)

32
8.130073547363281e-05


3.4.7 The Need for Speed: vector vs for loop
We utilized the NumPy library because it improves speed memory efficiency. Let's demonstrate:

In [185]:
np.random.seed(1)

a = np.random.rand(10000000)
b = np.random.rand(10000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()
print(f"np.dot(a,b) = {c:.4f}")
print(f"Vectorized version duration : {1000*(toc - tic):.4f}ms ")

tic = time.time()
c = my_dot(a,b)
toc = time.time()

print(f"my_dot(a,b): {c:.4f}")
print(f"Loop version duration:{1000 * (toc - tic):.4f}ms")

np.dot(a,b) = 2501072.5817
Vectorized version duration : 15.1911ms 
my_dot(a,b): 2501072.5817
Loop version duration:2274.8003ms


4.2 NumPy Arrays
NumPy's basic data structure is an indexable, n-dimensional array containing elements of the same type (dtype). These were described earlier. Matrices have a two-dimensional (2-D) index [m,n].

In Course 1, 2-D matrices are used to hold training data. Training data is  𝑚
  examples by  𝑛
  features creating an (m,n) array. Course 1 does not do operations directly on matrices but typically extracts an example as a vector and operates on that. Below you will review:

data creation
slicing and indexing

4.3 Matrix Creation
The same functions that created 1-D vectors will create 2-D or n-D arrays. Here are some examples

Below, the shape tuple is provided to achieve a 2-D result. Notice how NumPy uses brackets to denote each dimension. Notice further than NumPy, when printing, will print one row per line.

In [206]:
a = np.zeros((1,5))
print(f'a shape = {a.shape}, a = {a}')

a = np.zeros((2,2))

print(f'a shape: {a.shape}, a = {a}')

a = np.random.random_sample((1,1))
print(a)

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape: (2, 2), a = [[0. 0.]
 [0. 0.]]
[[0.53516563]]
