In [2]:
import numpy as np


matr = np.array([[1,0,1],[0,1,0],[3,3,3]])

det = np.linalg.det(matr)
print(det)


-1.665334536937729e-16


In [4]:
import numpy as np

# Define the matrix
matrix = np.array([
    [1, 0, 1],
    [0, 1, 0],
    [3, 3, 3]
])

# Compute the determinant
det = np.linalg.det(matrix)

# Print the result
print("Determinant of the matrix is:", det)

Determinant of the matrix is: -1.665334536937729e-16


In [ ]:
# Day 1: NumPy Basics and Arrays

# Topics:

# Introduction to NumPy arrays.
# Array creation (1D, 2D, n-dimensional arrays).
# Array indexing and slicing.
# Basic array operations (addition, subtraction, multiplication, division).
# Practice:
# Create vectors and matrices using NumPy.
# Perform basic arithmetic operations on arrays.
# Relevant Linear Algebra Topic:
# Vectors, scalars, and matrices.


In [2]:
# Introduction to NumPy arrays.

import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [4]:
arr_2d = np.array([[1,2,3,4],[1,2,3,4]])
print(arr_2d)

[[1 2 3 4]
 [1 2 3 4]]


In [20]:
arr = np.arange(1,10,3)
print(arr)

[1 4 7]


In [24]:
arr = np.linspace(1,10,3)
print(arr)

[ 1.   5.5 10. ]


In [42]:
arr = np.zeros((3,3))
print(arr)
arr = np.zeros((1,2))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0.]]


In [46]:
arr = np.ones((1,2))
print(arr)

[[1. 1.]]


In [40]:
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [93]:
arr = np.random.rand(1,2)
print(arr)

[[0.04036626 0.41720627]]


In [95]:
# basic operations on numpy array

arr = np.array([1,2,3,4])
print(arr + 3)
print(arr * 3)

[4 5 6 7]
[ 3  6  9 12]


In [105]:
# array alicing

arr = np.array([[1,2,3],[8,9,10]])
print(arr[0,1])
print(arr[:,1])
print(arr[::2])

2
[2 9]
[[1 2 3]]


In [107]:
arr = np.array([[1,2,3,4],[1,2,3,4]])
val = arr.shape
print(val)

(2, 4)


In [109]:
reshape = arr.reshape(4,2)
print(reshape)

[[1 2]
 [3 4]
 [1 2]
 [3 4]]


In [113]:
arr = np.array([1,2,3,4,5])
print(arr.sum())
print(arr.mean())
print(arr.std())


15
3.0
1.4142135623730951


In [123]:
arr = np.array([1,2,3,4])
print(arr.ndim)

1


In [127]:
arr = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(arr.ndim)

2


In [135]:
# creating 3d array

arr = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]]]
3


In [149]:
arr_4d = np.zeros((2,2,2,2))
print(arr_4d)

[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


In [151]:
one_arr = np.ones((2,3))
print(one_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [153]:
arr_3d = np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,9]]])
print(arr_3d[1,1,2])


9


In [157]:
arr = np.array([2,3,4,5,6])
print(arr[::-1])

[6 5 4 3 2]


In [169]:
arr_2d = np.array([[1,2,3],[1,2,3],[9,2,3],[1,2,9]])
print(arr_2d[:3])

[[1 2 3]
 [1 2 3]
 [9 2 3]]


In [163]:
print(arr_2d[:,:2])

[[1 2]
 [1 2]
 [1 2]
 [1 2]]


In [165]:
print(arr_2d[-1])

[1 2 9]


In [171]:
print(arr_2d > 2)


[[False False  True]
 [False False  True]
 [ True False  True]
 [False False  True]]


In [177]:
arr  = np.array([22,3,44,55,66])
print(arr[arr > 3])

[22 44 55 66]


In [179]:
arr_2d = np.array([[1,2,3],[7,2,6],[9,2,3],[1,2,9]])
print(arr_2d[1,::2])

[7 6]


In [181]:
# element wise addition

arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
print(arr1+arr2)

[ 6  8 10 12]


In [189]:
# using func

result = np.add(arr2,arr1)
print(result)

[ 6  8 10 12]


In [191]:
print(arr1-arr2)

[-4 -4 -4 -4]


In [193]:
sub  = np.subtract(arr1,arr2)
print(sub)

[-4 -4 -4 -4]


In [195]:
mult = np.multiply(arr1,arr2)
print(mult)

[ 5 12 21 32]


In [197]:
devide = np.divide(arr1,arr2)
print(devide)

[0.2        0.33333333 0.42857143 0.5       ]


In [219]:
power = arr1 **2
print(power)

power = np.power(arr1,arr2)
print(power)

[ 1  4  9 16]
[    1    64  2187 65536]


In [217]:
mod = arr2 % arr1
print(mod)

mod = np.mod(arr2,arr1)
print(mod)

[0 0 1 0]
[0 0 1 0]


In [225]:
# broadcasting
arr = np.array([1,2,3,4])
broadcast = arr + 10
mul_bro = arr * 10
print(broadcast)
print(mul_bro)


[11 12 13 14]
[10 20 30 40]


In [227]:
arr += 10
print(arr)

[11 12 13 14]


In [229]:
vector = np.array([1,3,4,5])
print(vector)

[1 3 4 5]


In [233]:
diagonal_mat = np.diag([1,2,9])
print(diagonal_mat)

[[1 0 0]
 [0 2 0]
 [0 0 9]]


In [ ]:
# day 2: Matrix Operations

# Topics:

# Element-wise operations (addition, subtraction).
# Dot product between two vectors.
# Matrix multiplication (np.dot or @).

# Practice:

# Implement basic vector operations using NumPy.
# Multiply matrices and vectors using np.dot.
# Relevant Linear Algebra Topic:
# Matrix-vector multiplication, dot product.



In [29]:
import numpy as np

matrix_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_b = np.array([[9,7,6],[5,3,2],[5,6,7]])
add = np.add(matrix_a,matrix_b)
subtract = np.subtract(matrix_a,matrix_b)
divide = np.divide(matrix_a,matrix_b)
multiply = np.multiply(matrix_a,matrix_b)
det = np.linalg.det(matrix_a)
dot = np.dot(matrix_a,matrix_b)
print(dot)
print(add)
print(subtract)
print(divide)
print(multiply)
print(det)

[[ 34  31  31]
 [ 91  79  76]
 [148 127 121]]
[[10  9  9]
 [ 9  8  8]
 [12 14 16]]
[[-8 -5 -3]
 [-1  2  4]
 [ 2  2  2]]
[[0.11111111 0.28571429 0.5       ]
 [0.8        1.66666667 3.        ]
 [1.4        1.33333333 1.28571429]]
[[ 9 14 18]
 [20 15 12]
 [35 48 63]]
-9.51619735392994e-16


In [37]:

# represent the system as a matrix and vector

A = np.array([[1,1,-1],[1,-1,2],[4,-2,1]])
B = np.array([6,4,10])

det = np.linalg.det(A)

if det != 0:
    solution = np.linalg.solve(A,B)
else:
    solution = None

print(det,solution)

7.999999999999998 [4. 4. 2.]


In [ ]:
# Day 3: Matrix Properties

# Topics:

# Transpose of a matrix (np.transpose or .T).
# Identity matrix (np.eye).
# Diagonal matrix (np.diag).

# Practice:

# Create a matrix, find its transpose, and work with identity matrices.
# Understand diagonal matrix applications in NumPy.
# Relevant Linear Algebra Topic:
# Transpose, identity matrix, diagonal matrix.


In [6]:
import numpy as np

# Creating a 3x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Finding the transpose of the matrix
transpose_matrix = matrix.T
transpose_matrix2 = np.transpose(matrix)

print("Original Matrix:\n", matrix)
print("Transpose of the Matrix:\n", transpose_matrix)
print("Transpose of the matrix: \n", transpose_matrix2)


Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of the Matrix:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpose of the matrix: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [10]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
diagonal = np.diag([2,3,4,5,6,7])
print(diagonal)

[[2 0 0 0 0 0]
 [0 3 0 0 0 0]
 [0 0 4 0 0 0]
 [0 0 0 5 0 0]
 [0 0 0 0 6 0]
 [0 0 0 0 0 7]]


In [20]:
# Create a matrix
matrix = np.array([[5, 1, 3],
                   [7, 4, 6],
                   [9, 8, 2]])

# Extract the diagonal elements
diagonal_elements = np.diag(matrix)

print("\nDiagonal Elements:")
print(diagonal_elements)



Diagonal Elements:
[5 4 2]


In [22]:
# Create a matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create a diagonal matrix
diagonal_matrix = np.diag([1, 2, 3])

# Multiply the matrix with the diagonal matrix
result = np.dot(diagonal_matrix, matrix)

print("\nResult of Multiplying with Diagonal Matrix:")
print(result)



Result of Multiplying with Diagonal Matrix:
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]
